### PR TITLE
Removed all warnings in tests.

### PR DESCRIPTION
**Pull request by dzejkobi**
Removed all warnings in tests.

- Removed .order_by() in  feder/cases/views.py to preserve default ordering, because base View supports pagination and expects queryset to be ordered.
- Changed recent() method in feder/letters/models.py to use Timezone aware timestamp.

### CODE REVIEW

**Comment by ad-m** [comment]
Did you considered performance impact when enabled sorting? See also when it was introduced https://github.com/watchdogpolska/feder/commit/b2936392b8a71aea72d4ebd9f9b76410f2434ace .

**Comment by dzejkobi** [comment]
Yes, I supposed it shouldn't be an issue. But if You say, that it is in this case, I restored previous code.

**Comment by ad-m** [comment]
We order by created by default ( https://github.com/watchdogpolska/feder/blob/master/feder/cases/models.py#L85 ). Our created field is not indexed ( https://github.com/jazzband/django-model-utils/blob/master/model_utils/models.py ). All in all, maybe we should index this field, which will allow us to sort faster throughout entire application?

**Comment by ad-m** [comment]
@dzejkobi , możesz zrobić rebase? Z nieznanych powodów nie wystartował GitHub Actions, a chciałbym zobaczyć zielone testy przed wcieleniem.

**Comment by ad-m** [comment]
LGTM. Tests pass.

**Pull request merged**
